name: Test
on: [ push, pull_request ]

jobs:
  build:
    environment: BAIDU_SDK
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Build all
        run: ./gradlew assemble --scan

      - name: Test AipContentCensor
        run: ./gradlew baidu-aip:test --tests "xyz.cssxsh.baidu.aip.AipContentCensorTest" --scan --info

      - name: Test AipTextToSpeech
        run: ./gradlew baidu-aip:test --tests "xyz.cssxsh.baidu.aip.AipTextToSpeechTest" --scan --info

      - name: Test BaiduUnitClient
        run: ./gradlew baidu-unit:test --tests "xyz.cssxsh.baidu.unit.BaiduUnitClientTest" --scan --info