name: Test
on: [ push, pull_request ]

jobs:
  aip:
    environment: BAIDU_SDK
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Build all
        run: ./gradlew assemble --scan

      - name: Test AipContentCensor
        run: ./gradlew baidu-aip:test --tests "xyz.cssxsh.baidu.aip.AipContentCensorTest" --scan --info
        env:
          BAIDU_CENSOR_APP_ID: ${{ secrets.BAIDU_CENSOR_APP_ID }}
          BAIDU_CENSOR_APP_KEY: ${{ secrets.BAIDU_CENSOR_APP_KEY }}
          BAIDU_CENSOR_APP_NAME: ${{ secrets.BAIDU_CENSOR_APP_NAME }}
          BAIDU_CENSOR_SECRET_KEY: ${{ secrets.BAIDU_CENSOR_SECRET_KEY }}

      - name: Test AipTextToSpeech
        run: ./gradlew baidu-aip:test --tests "xyz.cssxsh.baidu.aip.AipTextToSpeechTest" --scan --info
        env:
          BAIDU_TTS_APP_ID: ${{ secrets.BAIDU_TTS_APP_ID }}
          BAIDU_TTS_APP_KEY: ${{ secrets.BAIDU_TTS_APP_KEY }}
          BAIDU_TTS_APP_NAME: ${{ secrets.BAIDU_TTS_APP_NAME }}
          BAIDU_TTS_SECRET_KEY: ${{ secrets.BAIDU_TTS_SECRET_KEY }}

      - name: Test AipTranslator
        run: ./gradlew baidu-aip:test --tests "xyz.cssxsh.baidu.aip.AipTranslatorTest" --scan --info
        env:
          BAIDU_MT_APP_ID: ${{ secrets.BAIDU_MT_APP_ID }}
          BAIDU_MT_APP_KEY: ${{ secrets.BAIDU_MT_APP_KEY }}
          BAIDU_MT_APP_NAME: ${{ secrets.BAIDU_MT_APP_NAME }}
          BAIDU_MT_SECRET_KEY: ${{ secrets.BAIDU_MT_SECRET_KEY }}

      - name: Test BaiduUnitClient
        run: ./gradlew baidu-unit:test --tests "xyz.cssxsh.baidu.unit.BaiduUnitClientTest" --scan --info
        env:
          BAIDU_UNIT_APP_ID: ${{ secrets.BAIDU_UNIT_APP_ID }}
          BAIDU_UNIT_APP_KEY: ${{ secrets.BAIDU_UNIT_APP_KEY }}
          BAIDU_UNIT_APP_NAME: ${{ secrets.BAIDU_UNIT_APP_NAME }}
          BAIDU_UNIT_SECRET_KEY: ${{ secrets.BAIDU_UNIT_SECRET_KEY }}
  netdisk:
    environment: BAIDU_NETDISK_SDK
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Build all
        run: ./gradlew assemble --scan

      - name: Test BaiduNetDiskRESTfulTest
        run: ./gradlew baidu-netdisk:test --tests "xyz.cssxsh.baidu.disk.BaiduNetDiskRESTfulTest" --scan --info
        env:
          BAIDU_NETDISK_APP_ID: ${{ secrets.BAIDU_NETDISK_APP_ID }}
          BAIDU_NETDISK_APP_NAME: ${{ secrets.BAIDU_NETDISK_APP_NAME }}
          BAIDU_NETDISK_APP_KEY: ${{ secrets.BAIDU_NETDISK_APP_KEY }}
          BAIDU_NETDISK_SECRET_KEY: ${{ secrets.BAIDU_NETDISK_SECRET_KEY }}
          BAIDU_NETDISK_SHARE_SECRET: ${{ secrets.BAIDU_NETDISK_SHARE_SECRET }}
          BAIDU_NETDISK_SHARE_THIRD_ID: ${{ secrets.BAIDU_NETDISK_SHARE_THIRD_ID }}
          BAIDU_NETDISK_ACCESS_TOKEN: ${{ secrets.BAIDU_NETDISK_ACCESS_TOKEN }}
          BAIDU_NETDISK_REFRESH_TOKEN: ${{ secrets.BAIDU_NETDISK_REFRESH_TOKEN }}

      - name: Test BaiduNetDiskWebTest
        run: ./gradlew baidu-netdisk:test --tests "xyz.cssxsh.baidu.disk.BaiduNetDiskWebTest" --scan --info
        env:
          BAIDU_NETDISK_APP_ID: ${{ secrets.BAIDU_NETDISK_APP_ID }}
          BAIDU_NETDISK_APP_NAME: ${{ secrets.BAIDU_NETDISK_APP_NAME }}
          BAIDU_NETDISK_APP_KEY: ${{ secrets.BAIDU_NETDISK_APP_KEY }}
          BAIDU_NETDISK_SECRET_KEY: ${{ secrets.BAIDU_NETDISK_SECRET_KEY }}
          BAIDU_NETDISK_SHARE_SECRET: ${{ secrets.BAIDU_NETDISK_SHARE_SECRET }}
          BAIDU_NETDISK_SHARE_THIRD_ID: ${{ secrets.BAIDU_NETDISK_SHARE_THIRD_ID }}
          BAIDU_NETDISK_ACCESS_TOKEN: ${{ secrets.BAIDU_NETDISK_ACCESS_TOKEN }}
          BAIDU_NETDISK_REFRESH_TOKEN: ${{ secrets.BAIDU_NETDISK_REFRESH_TOKEN }}

      - name: Test BaiduPersonalCloudStorageTest
        run: ./gradlew baidu-netdisk:test --tests "xyz.cssxsh.baidu.disk.BaiduPersonalCloudStorageTest" --scan --info
        env:
          BAIDU_NETDISK_APP_ID: ${{ secrets.BAIDU_NETDISK_APP_ID }}
          BAIDU_NETDISK_APP_NAME: ${{ secrets.BAIDU_NETDISK_APP_NAME }}
          BAIDU_NETDISK_APP_KEY: ${{ secrets.BAIDU_NETDISK_APP_KEY }}
          BAIDU_NETDISK_SECRET_KEY: ${{ secrets.BAIDU_NETDISK_SECRET_KEY }}
          BAIDU_NETDISK_SHARE_SECRET: ${{ secrets.BAIDU_NETDISK_SHARE_SECRET }}
          BAIDU_NETDISK_SHARE_THIRD_ID: ${{ secrets.BAIDU_NETDISK_SHARE_THIRD_ID }}
          BAIDU_NETDISK_ACCESS_TOKEN: ${{ secrets.BAIDU_NETDISK_ACCESS_TOKEN }}
          BAIDU_NETDISK_REFRESH_TOKEN: ${{ secrets.BAIDU_NETDISK_REFRESH_TOKEN }}
